import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms and conditions for using Aura English.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white selection:bg-blue-100 selection:text-blue-900">
      {/* Header Spacer */}
      <div className="h-24 md:h-32 bg-slate-50 border-b border-slate-100"></div>

      <div className="max-w-3xl mx-auto px-6 py-16 md:py-24">
        <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-8 tracking-tight">
          Terms of Use
        </h1>
        <p className="text-slate-500 mb-12 font-medium">Last updated: March 25, 2026</p>

        <div className="prose prose-slate prose-lg max-w-none text-slate-700 space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Aura English (the "Application") and its 
              associated website, you agree to be bound by these Terms of Use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              2. Open Source & License
            </h2>
            <p>
              Aura English is an open-source project. You may use, modify, and 
              distribute the source code in accordance with the licenses specified 
              in the project's GitHub repository.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              3. AI Features & User Responsibilities
            </h2>
            <p>
              The Application allows you to integrate third-party AI services 
              (e.g., Google Gemini) by providing your own API key.
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>
                <strong>API Key Usage:</strong> You are solely responsible for 
                obtaining and maintaining your own API keys and for any costs 
                incurred through their use.
              </li>
              <li>
                <strong>Content Accuracy:</strong> AI-generated content is provided 
                "as is". Aura English is not responsible for the accuracy or 
                suitability of sentences or feedback generated by AI.
              </li>
              <li>
                <strong>Ethics:</strong> You agree not to use the Application for 
                any illegal, harmful, or unethical purposes.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              4. Disclaimer of Warranty
            </h2>
            <p className="italic">
              THE APPLICATION IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
              EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
              IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
              CLAIM, DAMAGES OR OTHER LIABILITY.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              5. Limitation of Liability
            </h2>
            <p>
              In no event shall Aura English or its contributors be liable for any 
              direct, indirect, incidental, special, or consequential damages 
              arising out of or in connection with your use of the Application.
            </p>
          </section>

          <section className="pt-8 border-t border-slate-100">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Contact</h2>
            <p>
              For any legal inquiries, please open an issue on our official 
              GitHub repository.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
